recommended php settings and prod ready

diff --git a/wp/Dockerfile b/wp/Dockerfile
--- a/wp/Dockerfile
+++ b/wp/Dockerfile
@@ -45,6 +45,31 @@ COPY --from=wp /usr/src/wordpress /usr/src/wordpress
 COPY --from=wp /usr/local/etc/php/conf.d /usr/local/etc/php/conf.d/
 COPY --from=wp /usr/local/bin/docker-entrypoint.sh /usr/local/bin/
 
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
+RUN set -eux; \
+    { \
+    echo 'opcache.memory_consumption=128'; \
+    echo 'opcache.interned_strings_buffer=8'; \
+    echo 'opcache.max_accelerated_files=4000'; \
+    echo 'opcache.revalidate_freq=2'; \
+    } > $PHP_INI_DIR/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+    # https://www.php.net/manual/en/errorfunc.constants.php
+    # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+    } > $PHP_INI_DIR/conf.d/error-logging.ini
+
 # use frankenphp instead of php-fpm
 RUN sed -i \
     -e 's/\[ "$1" = '\''php-fpm'\'' \]/\[\[ "$1" == frankenphp* \]\]/g' \
@@ -58,7 +83,7 @@ RUN chown -R www-data:www-data /data/caddy && \
     chown -R www-data:www-data /usr/src/wordpress && \
     chown -R www-data:www-data /usr/local/bin/docker-entrypoint.sh
 
-COPY custom.ini /usr/local/etc/php/conf.d/
+COPY custom.ini $PHP_INI_DIR/conf.d/
 
 COPY Caddyfile /etc/caddy/
 
